language: java
service:
  - docker

addons:
  sonarcloud:
    organization: "franckyi"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Pcoverage -Dsonar.projectKey=Franckyi_sample-application-students
  - echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_USR" --password-stdin
  - docker build -t http sample-application-http-api-server
  - docker build -t db sample-application-db-changelog-job
  - docker tag http $DOCKERHUB_USR/tp2_http:1.0
  - docker tag db $DOCKERHUB_USR/tp2_db:1.0
  - docker push $DOCKERHUB_USR/tp2_http:1.0
  - docker push $DOCKERHUB_USR/tp2_db:1.0

cache:
  directories:
    - $HOME/.m2
