language: java
service:
  - docker

addons:
  sonarcloud:
    organization: "franckyi"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: build
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=Franckyi_sample-application-students
    - stage: deploy
      script: echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_USR" --password-stdin
    - script: docker build -t http sample-application-http-api-server
    - script: docker build -t db sample-application-db-changelog-job
    - script: docker tag http $DOCKERHUB_USR/tp2_http:1.0
    - script: docker tag db $DOCKERHUB_USR/tp2_db:1.0
    - script: docker push $DOCKERHUB_USR/tp2_http:1.0
    - script: docker push $DOCKERHUB_USR/tp2_db:1.0

cache:
  directories:
    - $HOME/.m2
